# Generated by Django 4.2.7 on 2023-11-28 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolClass', models.CharField(max_length=20)),
                ('className', models.CharField(max_length=20)),
                ('schoolClassChinese', models.CharField(max_length=20)),
                ('seatNumber', models.CharField(max_length=20)),
                ('studentID', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=30)),
                ('identityCard', models.CharField(max_length=30)),
                ('sex', models.CharField(max_length=2)),
                ('birth_date', models.DateField()),
            ],
        ),
    ]
