# Generated by Django 4.2.7 on 2023-11-28 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExcelDownload', '0002_rename_person_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='studentID',
            field=models.IntegerField(),
        ),
    ]
