# Generated by Django 4.2.5 on 2023-09-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="citrix_log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location_name", models.CharField(max_length=50)),
                ("user_name", models.CharField(max_length=50)),
                ("user_ip", models.CharField(max_length=50)),
                ("application_start_date", models.DateTimeField(null=True)),
                ("user_logon_start_date", models.DateTimeField(null=True)),
                ("session_start_date", models.DateTimeField(null=True)),
                ("session_end_date", models.DateTimeField(null=True)),
                ("connection_logon_date", models.DateTimeField(null=True)),
                ("application_end_date", models.DateTimeField(null=True)),
                ("application_id", models.CharField(max_length=100)),
                ("session_user_id", models.CharField(max_length=100)),
                ("application_sessionkey", models.CharField(max_length=100)),
            ],
        ),
    ]
