# Generated by Django 4.2.5 on 2023-09-19 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("database_model", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="citrix_log",
        ),
    ]
